### PR TITLE
message when you have no meetings

### PR DESCRIPTION
**Pull request by zbarnz**
### Ticket:
[Notion](https://www.notion.so/thomashudsonnotes/a1f3e7cd3bf74c62b06dbda78b2c9c7c?v=43d3f2b9730045f691cd254967c6949d&p=5c4e037cf38544d2933d96ba49fd83ed)

### Preview
image

### Merge Checklist
- [x] Correct Target Branch
- [x] Pre-Review Diff Check
- [x] PR Description
- [x] Add Reviewers and Assignees
- [ ] Review Complete
- [ ] Rebase
- [ ] Rebase Approved

### CODE REVIEW

**Comment by thudsonbu** [comment]
Since this is an inbox component we might actually want to reuse it at some point. Maybe we should pass the empty message as a prop?

**Comment by zbarnz** [comment]
@thudsonbu changed to pass in message

**Comment by thudsonbu** [comment]
@zbarnz Did you push that change?

**Comment by zbarnz** [comment]
@thudsonbu apparently not lol, I'll push it tonight

**Review by thudsonbu — APPROVED** [review]

**Pull request merged**
