### PR TITLE
refactor to class components, drawer state in ui slice, test improvem…

### PR DESCRIPTION
**Pull request by thudsonbu**
### Context

After coming to the realization that @Dahvd was right all along, class components suck. I have removed them from the app.

### Implementation

**Changes**

- remove class based components
- add `uiSlice` that keeps state for drawer (drawer stays closed or open across pages)
- fixed some tests and removed coverage test for db which is not possible to cover since it depends on environmental variables
- removed proptypes from remaining components
- fixed some other annoying errors

### Merge Checklist

- [ ] Correct Target Branch
- [ ] Pre-Review Diff Check
- [ ] PR Description
- [ ] Add Reviewers and Assignees
- [ ] Review Complete
- [ ] Rebase
- [ ] Rebase Approved

### CODE REVIEW

**Review by zbarnz — APPROVED** [review]
Holy crap that was fast

**Review by zbarnz — COMMENTED** [review]
Formatting and tests look great too nice job

**Comment by thudsonbu** [comment]
The tests can actually be a bit better if we use [chai](https://www.chaijs.com/) instead of the native assert. I am going to work on fixing them up this week.

**Review by Dahvd — APPROVED** [review]
Definitely approve of this even though I'm currently having problems because apparently class components are better for passing functions to or something?????

**Pull request merged**
