### PR TITLE
added meetings container

### PR DESCRIPTION
**Pull request by zbarnz**
### Context
  - Inbox UI looked a little ug to me

### Implementation
  - added container

### Preview
  
inbox

### Merge Checklist
- [x] Correct Target Branch
- [x] Pre-Review Diff Check
- [x] PR Description
- [x] Add Reviewers and Assignees
- [ ] Review Complete
- [ ] Rebase
- [ ] Rebase Approved

### CODE REVIEW

**Comment by thudsonbu** [comment]
Wait so what is this for?

**Comment by zbarnz** [comment]
> Wait so what is this for?

im confused. See picture?

**Comment by thudsonbu** [comment]
Is this for the meeting edit page?

**Review by thudsonbu — APPROVED** [review]

**Comment by zbarnz** [comment]
> Is this for the meeting edit page?

Inbox page, can you see the picture?

**Pull request merged**
