### PR TITLE
Add support for workspaces.

### PR DESCRIPTION
**Pull request by thudsonbu**
Co-authored-by: zbarnz <zbarnz@yahoo.com>
Co-authored-by: dahvd <davidoligney@gmail.com>

You should have been here.

### CODE REVIEW

**Review by zbarnz — APPROVED** [review]
You really shoulve seen it

**Comment by thudsonbu** [comment]
What a time it was

**Review by Dahvd — APPROVED** [review]
No

**Review by thudsonbu — COMMENTED** [review]
comment

**Pull request merged**
